SELECT SB2.R_E_C_N_O_ AS B2RECCNO,
       SD4.D4_FILIAL,
       SD4.D4_COD,
       SD4.D4_OP,
       SD4.D4_TRT,
       SD4.D4_LOTECTL,
       SD4.D4_NUMLOTE,
       SD4.D4_LOCAL,
       SD4.D4_ORDEM,
       SD4.D4_OPORIG,
       SD4.D4_SEQ,
       ISNULL(SUM(SD4.D4_QUANT), 0) + ISNULL(SUM(SDD.DD_QUANT), 0) AS QTDEMP
FROM SB2070 SB2
LEFT JOIN SD4070 SD4
  ON SD4.D4_FILIAL    = SB2.B2_FILIAL
 AND SD4.D4_COD       = SB2.B2_COD
 AND SD4.D4_LOCAL     = SB2.B2_LOCAL
 AND SD4.D4_QUANT    <> 0
 AND SD4.D_E_L_E_T_   = ' '
LEFT JOIN SDD070 SDD
  ON SDD.DD_FILIAL    = SB2.B2_FILIAL
 AND SDD.DD_PRODUTO   = SB2.B2_COD
 AND SDD.DD_LOCAL     = SB2.B2_LOCAL
 AND SDD.DD_QUANT    <> 0
 AND SDD.D_E_L_E_T_   = ' '
WHERE SB2.D_E_L_E_T_  = ' '
  AND SB2.B2_FILIAL   = '01'
  AND SB2.B2_COD     >= 'CR19           '
  AND SB2.B2_COD     <= 'CR19           '
  AND SB2.B2_LOCAL   >= '02'
  AND SB2.B2_LOCAL   <= '02'
GROUP BY SB2.R_E_C_N_O_,
         SD4.D4_FILIAL,
         SD4.D4_COD,
         SD4.D4_OP,
         SD4.D4_TRT,
         SD4.D4_LOTECTL,
         SD4.D4_NUMLOTE,
         SD4.D4_LOCAL,
         SD4.D4_ORDEM,
         SD4.D4_OPORIG,
         SD4.D4_SEQ
